export enum Modulos {
  MODULE_REGISTRO_USER = 'REGISTRO_USUARIOS',
  MODULE_REGISTRO_CONTADORES = 'REGISTRO_CONTADORES',
  MODULE_LOGIN = 'LOGIN',
  MODULE_REGISTRO_EMISORES = 'REGISTRO_EMISORES',
  MODULE_REGISTRO_EMISORES_CONTADORES = 'REGISTRO_EMISORES_CONTADORES',
  MODULE_REGISTRO_UTILS = 'REGISTRO_UTILS',
  MODULE_EMISION_DOCUMENTOS_CONTADORES = 'EMISION_DOCUMENTOS_CONTADORES',
  MODULE_EJEMPLO = 'EJEMPLO',
  PAGE_SIZE = 10,



  // cuenta para empresas

  MODULE_EMPRESA_CONFI = 'CONFIGURACION_EMPRESA',
}
